package cloud.mallne.geokit.coordinates.ast.expression

sealed interface DerivedGeodeticCoordinateReferenceSystem : SingleCoordinateReferenceSystem,
    StaticCrsCoordinateMetadata, DynamicCrsCoordinateMetadata