### WFS 2.0.0 GET Request (KVP BBOX Filter - OGC Compliant Y, X Order)
@feature_type = nora:v_al_flurstueck
@version = 2.0.0
@crs_urn = urn:ogc:def:crs:EPSG::4326
@max_features = 10
@encodedFilter = %3Cfes%3AFilter%20xmlns%3Afes%3D%22http%3A%2F%2Fwww.opengis.net%2Ffes%2F2.0%22%3E%3Cfes%3ABBOX%3E%3Cgml%3AEnvelope%20xmlns%3Agml%3D%22http%3A%2F%2Fwww.opengis.net%2Fgml%2F3.2%22%20srsName%3D%22urn%3Aogc%3Adef%3Acrs%3AEPSG%3A%3A4326%22%3E%3Cgml%3AlowerCorner%3E48.2358%208.0027%3C%2Fgml%3AlowerCorner%3E%3Cgml%3AupperCorner%3E48.2379%208.0045%3C%2Fgml%3AupperCorner%3E%3C%2Fgml%3AEnvelope%3E%3C%2Ffes%3ABBOX%3E%3C%2Ffes%3AFilter%3E

GET https://owsproxy.lgl-bw.de/owsproxy/wfs/WFS_LGL-BW_ALKIS?
    SERVICE=WFS&
    VERSION={{version}}&
    REQUEST=GetFeature&
    typeNames=nora:v_al_flurstueck&
    SRSName={{crs_urn}}&
    count={{max_features}}

### GET Capabilities
GET https://owsproxy.lgl-bw.de/owsproxy/wfs/WFS_LGL-BW_ALKIS?
    service=wfs&
    version={{version}}&
    request=GetCapabilities

### POST Capabilities
POST https://owsproxy.lgl-bw.de/owsproxy/wfs/WFS_LGL-BW_ALKIS
Content-Type: text/xml

<GetCapabilities
        service="WFS"
        xmlns="http://www.opengis.net/wfs"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.1.0/wfs.xsd"/>

### WFS 2.0.0 GET Request (KVP BBOX Filter - OGC Compliant Y, X Order)
GET https://www.geoproxy.geoportal-th.de/geoproxy/services/adv_alkis_wfs?
    SERVICE=WFS&
    VERSION={{version}}&
    REQUEST=GetFeature&
    typeNames={{feature_type}}&
    SRSName={{crs_urn}}&
    bbox=645021.4301836416,5647295.731612682,645406.5624732533,5646594.367474664&
    count={{max_features}}

### WFS 2.0.0 GET Request (KVP BBOX Filter - OGC Compliant Y, X Order)
POST https://www.geoproxy.geoportal-th.de/geoproxy/services/adv_alkis_wfs
Content-Type: application/xml

<wfs:GetFeature
        service="WFS"
        version="2.0.0"
        xmlns:wfs="http://www.opengis.net/wfs/2.0"
        xmlns:fes="http://www.opengis.net/fes/2.0"
        xmlns:gml="http://www.opengis.net/gml/3.2"
        count="{{max_features}}">
    <wfs:Query typeNames="{{feature_type}}" srsName="urn:ogc:def:crs:EPSG::4326">
        <fes:Filter>
            <fes:BBOX>
                    <gml:Envelope srsName="urn:ogc:def:crs:EPSG::4326">
                        <gml:lowerCorner>50.9526 11.0650</gml:lowerCorner>
                        <gml:upperCorner>50.9590 11.0702</gml:upperCorner>
                    </gml:Envelope>
            </fes:BBOX>
        </fes:Filter>
    </wfs:Query>
</wfs:GetFeature>

### TEST
POST https://owsproxy.lgl-bw.de/owsproxy/wfs/WFS_LGL-BW_ALKIS
Content-Type: text/xml

<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs/2.0" service="WFS" version="2.0.0" count="2000">
    <wfs:Query typeNames="nora:v_al_flurstueck" srsName="urn:ogc:def:crs:EPSG::4326">
        <fes:Filter xmlns:fes="http://www.opengis.net/fes/2.0">
            <fes:BBOX>
                <gml:Envelope xmlns:gml="http://www.opengis.net/gml/3.2" srsName="urn:ogc:def:crs:EPSG::4326">
                    <gml:lowerCorner>48.2358 8.0027</gml:lowerCorner>
                    <gml:upperCorner>48.2379 8.0045</gml:upperCorner>
                </gml:Envelope>
            </fes:BBOX>
        </fes:Filter>
    </wfs:Query>
</wfs:GetFeature>

###Options
OPTIONS https://owsproxy.lgl-bw.de/owsproxy/wfs/WFS_LGL-BW_ALKIS?
    SERVICE=WFS&
    VERSION={{version}}&
    REQUEST=GetFeature

###GET
GET https://owsproxy.lgl-bw.de/owsproxy/wfs/WFS_LGL-BW_ALKIS?SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&
    TYPENAMES=nora:v_al_flurstueck&STARTINDEX=0&COUNT=1000000&SRSNAME=urn:ogc:def:crs:EPSG::25832&
    BBOX=521585.12448141304776073,5345508.89440889004617929,530044.62538361875340343,5349880.48515886906534433,urn:ogc:def:crs:EPSG::25832

### POST
GET https://owsproxy.lgl-bw.de/owsproxy/wfs/WFS_LGL-BW_ALKIS?
    SERVICE=WFS&
    REQUEST=GetFeature&
    VERSION=2.0.0&
    TYPENAMES=nora:v_al_flurstueck&
    COUNT=1000000&
    SRSNAME=urn:ogc:def:crs:EPSG::4326&
    FILTER={{encodedFilter}}