### WFS 2.0.0 GET Request (KVP BBOX Filter - OGC Compliant Y, X Order)
@feature_type = ave:Flurstueck
@version = 2.0.0
@crs_urn = urn:ogc:def:crs:EPSG::4326
@max_features = 10
GET https://owsproxy.lgl-bw.de/owsproxy/wfs/WFS_LGL-BW_ALKIS?
    SERVICE=WFS&
    VERSION={{version}}&
    REQUEST=GetFeature&
    typeNames=nora:v_al_flurstueck&
    SRSName={{crs_urn}}&
    count={{max_features}}

### WFS 2.0.0 GET Request (KVP BBOX Filter - OGC Compliant Y, X Order)
GET https://www.geoproxy.geoportal-th.de/geoproxy/services/adv_alkis_wfs?
    SERVICE=WFS&
    VERSION={{version}}&
    REQUEST=GetFeature&
    typeNames={{feature_type}}&
    SRSName={{crs_urn}}&
    bbox=645021.4301836416,5647295.731612682,645406.5624732533,5646594.367474664&
    count={{max_features}}

### WFS 2.0.0 GET Request (KVP BBOX Filter - OGC Compliant Y, X Order)
POST https://www.geoproxy.geoportal-th.de/geoproxy/services/adv_alkis_wfs
Content-Type: application/xml

<wfs:GetFeature
        service="WFS"
        version="2.0.0"
        xmlns:wfs="http://www.opengis.net/wfs/2.0"
        xmlns:fes="http://www.opengis.net/fes/2.0"
        xmlns:gml="http://www.opengis.net/gml/3.2"
        count="{{max_features}}">
    <wfs:Query typeNames="{{feature_type}}" srsName="urn:ogc:def:crs:EPSG::4326">
        <fes:Filter>
            <fes:BBOX>
                    <gml:Envelope srsName="urn:ogc:def:crs:EPSG::4326">
                        <gml:lowerCorner>50.9526 11.0650</gml:lowerCorner>
                        <gml:upperCorner>50.9590 11.0702</gml:upperCorner>
                    </gml:Envelope>
            </fes:BBOX>
        </fes:Filter>
    </wfs:Query>
</wfs:GetFeature>

### TEST
POST https://www.geoproxy.geoportal-th.de/geoproxy/services/adv_alkis_wfs
Content-Type: application/xml

<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs/2.0" service="WFS" version="2.0.0" count="20">
    <wfs:Query typeNames="ave:Flurstueck" srsName="urn:ogc:def:crs:EPSG::4326">
        <fes:Filter xmlns:fes="http://www.opengis.net/fes/2.0">
            <fes:BBOX>
                <gml:Envelope xmlns:gml="http://www.opengis.net/gml/3.2" srsName="urn:ogc:def:crs:EPSG::4326">
                    <gml:lowerCorner>50.9529 11.0650</gml:lowerCorner>
                    <gml:upperCorner>50.9593 11.0702</gml:upperCorner>
                </gml:Envelope>
            </fes:BBOX>
        </fes:Filter>
    </wfs:Query>
</wfs:GetFeature>