@feature_type = nora:v_al_flurstueck
@version = 2.0.0
@crs_urn = urn:ogc:def:crs:EPSG::4326
@max_features = 10
@server = https://owsproxy.lgl-bw.de/owsproxy/wfs/WFS_LGL-BW_ALKIS
@lowerLon = 48.2358
@lowerLat = 8.0027
@upperLon = 48.2379
@upperLat = 8.0045

### GET Capabilities
GET {{server}}?
    service=WFS&
    version={{version}}&
    request=GetCapabilities

### POST Capabilities
POST {{server}}
Content-Type: text/xml

<GetCapabilities
        service="WFS"
        xmlns="http://www.opengis.net/wfs"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.1.0/wfs.xsd"/>

### WFS 2.0.0 GET Request (KVP BBOX Filter - OGC Compliant Y, X Order)
POST {{server}}
Content-Type: application/xml

<wfs:GetFeature
        service="WFS"
        version="{{version}}"
        xmlns:wfs="http://www.opengis.net/wfs/2.0"
        xmlns:fes="http://www.opengis.net/fes/2.0"
        xmlns:gml="http://www.opengis.net/gml/3.2"
        count="{{max_features}}">
    <wfs:Query typeNames="{{feature_type}}" srsName="{{crs_urn}}">
        <fes:Filter>
            <fes:BBOX>
                    <gml:Envelope srsName="{{crs_urn}}">
                        <gml:lowerCorner>{{lowerLon}} {{lowerLat}}</gml:lowerCorner>
                        <gml:upperCorner>{{upperLon}} {{upperLat}}</gml:upperCorner>
                    </gml:Envelope>
            </fes:BBOX>
        </fes:Filter>
    </wfs:Query>
</wfs:GetFeature>

### WFS Filter Request as a GET
< {%
	const crs_urn = "urn:ogc:def:crs:EPSG::4326"
	const lowerLon = "48.2358"
	const lowerLat = "8.0027"
	const upperLon = "48.2379"
	const upperLat = "8.0045"

	const rawXml = `<fes:Filter xmlns:fes="http://www.opengis.net/fes/2.0" xmlns:gml="http://www.opengis.net/gml/3.2"><fes:BBOX><gml:Envelope srsName="${crs_urn}"><gml:lowerCorner>${lowerLon} ${lowerLat}</gml:lowerCorner><gml:upperCorner>${upperLon} ${upperLat}</gml:upperCorner></gml:Envelope></fes:BBOX></fes:Filter>`
	const encoded = encodeURIComponent(rawXml)
	client.global.set("encodedFilter", encoded)
%}
GET https://owsproxy.lgl-bw.de/owsproxy/wfs/WFS_LGL-BW_ALKIS?
    SERVICE=WFS&
    REQUEST=GetFeature&
    VERSION=2.0.0&
    TYPENAMES=nora:v_al_flurstueck&
    COUNT=1000000&
    SRSNAME=urn:ogc:def:crs:EPSG::4326&
    FILTER={{encodedFilter}}